// frontend/src/lib/components/report/CountUp.tsx

import { useEffect, useRef, useState } from 'react';
import { tweenNumber } from '$lib/utils/motion';
import { cn } from '$lib/utils/cn';

export interface CountUpProps {
  to: number;
  from?: number;
  duration?: number;
  decimals?: number;
  immediate?: boolean;
  className?: string;
}

export default function CountUp({
  to,
  from = 0,
  duration = 1100,
  decimals = 0,
  immediate = false,
  className,
}: CountUpProps) {
  const [value, setValue] = useState(from);
  const startedRef = useRef(false);
  const cancelRef = useRef<(() => void) | null>(null);
  const spanRef = useRef<HTMLSpanElement>(null);

  const start = () => {
    if (startedRef.current) return;
    startedRef.current = true;
    cancelRef.current?.();
    cancelRef.current = tweenNumber(from, to, duration, setValue);
  };

  useEffect(() => {
    if (immediate) start();
    return () => cancelRef.current?.();
  }, [immediate, from, to, duration]);

  useEffect(() => {
    if (immediate) return;
    const el = spanRef.current;
    if (!el || typeof IntersectionObserver === 'undefined') {
      start();
      return;
    }
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          start();
          obs.disconnect();
        }
      },
      { threshold: 0.4 },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [immediate]);

  return (
    <span ref={spanRef} className={cn(className)}>
      {value.toFixed(decimals)}
    </span>
  );
}

// frontend/src/lib/components/report/CountUp.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { inView, tweenNumber } from '$lib/utils/motion';

  export let to: number;
  export let from: number = 0;
  export let duration: number = 1100;
  export let decimals: number = 0;
  /** Force start immediately rather than on intersection. */
  export let immediate: boolean = false;
  let className: string = '';
  export { className as class };

  let value = from;
  let cancel: (() => void) | null = null;
  let started = false;

  function start() {
    if (started) return;
    started = true;
    cancel?.();
    cancel = tweenNumber(from, to, duration, (v) => (value = v));
  }

  onDestroy(() => cancel?.());

  $: display = value.toFixed(decimals);
  $: if (immediate && !started) start();
</script>

<span use:inView={{ threshold: 0.4, onEnter: start }} class={className}>{display}</span>
