// frontend/src/lib/components/report/StaggeredText.tsx

import { useEffect, useRef, useState } from 'react';
import { cn } from '$lib/utils/cn';

export interface StaggeredTextProps {
  text: string;
  stagger?: number;
  duration?: number;
  delay?: number;
  immediate?: boolean;
  className?: string;
}

export default function StaggeredText({
  text,
  stagger = 55,
  duration = 500,
  delay = 0,
  immediate = false,
  className,
}: StaggeredTextProps) {
  const ref = useRef<HTMLSpanElement>(null);
  const [visible, setVisible] = useState(immediate);
  const words = text.split(/(\s+)/);

  useEffect(() => {
    if (immediate) {
      setVisible(true);
      return;
    }
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          obs.disconnect();
        }
      },
      { threshold: 0.3 },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [immediate]);

  return (
    <span
      ref={ref}
      className={cn('gs-stagger', visible && 'is-in', className)}
      style={{ '--gs-d': `${duration}ms` } as React.CSSProperties}
    >
      {words.map((w, i) =>
        w.trim() === '' ? (
          <span key={i} className="whitespace-pre">
            {w}
          </span>
        ) : (
          <span
            key={i}
            className="gs-word"
            style={{ '--gs-delay': `${delay + i * stagger}ms` } as React.CSSProperties}
          >
            {w}
          </span>
        ),
      )}
    </span>
  );
}

// frontend/src/lib/components/report/StaggeredText.svelte
<script lang="ts">
  import { inView } from '$lib/utils/motion';

  /** The text to reveal word-by-word. */
  export let text: string;
  /** ms between word reveals. */
  export let stagger: number = 55;
  /** Per-word duration in ms. */
  export let duration: number = 500;
  /** Optional initial delay in ms. */
  export let delay: number = 0;
  /** Force reveal on mount. */
  export let immediate: boolean = false;
  let className: string = '';
  export { className as class };

  $: words = text.split(/(\s+)/);

  let visible = immediate;
  const onEnter = () => (visible = true);
</script>

<span
  class="gs-stagger {className}"
  class:is-in={visible}
  use:inView={{ threshold: 0.3, onEnter }}
  style="--gs-d: {duration}ms;"
>
  {#each words as w, i}
    {#if w.trim() === ''}
      <span class="whitespace-pre">{w}</span>
    {:else}
      <span class="gs-word" style="--gs-delay: {delay + i * stagger}ms;">{w}</span>
    {/if}
  {/each}
</span>

<style>
  .gs-stagger {
    display: inline;
  }
  .gs-word {
    display: inline-block;
    opacity: 0;
    transform: translateY(8px);
    transition:
      opacity var(--gs-d) cubic-bezier(0.22, 1, 0.36, 1) var(--gs-delay),
      transform var(--gs-d) cubic-bezier(0.22, 1, 0.36, 1) var(--gs-delay);
  }
  .is-in .gs-word {
    opacity: 1;
    transform: translateY(0);
  }
  @media (prefers-reduced-motion: reduce) {
    .gs-word {
      opacity: 1;
      transform: none;
      transition: none;
    }
  }
</style>
