// frontend/src/lib/components/home/InteractiveDemoPanel.tsx

import { useEffect, useRef, useState, type ElementType } from 'react';
import { cn } from '$lib/utils/cn';
import { prefersReducedMotion } from '$lib/utils/motion';
import { getDemoFlowSnapshot, useDemoFlow } from '$lib/hooks/demoFlow';
import DemoPanelInputState from './DemoPanelInputState';
import DemoPanelLoadingState from './DemoPanelLoadingState';
import DemoPanelResultState from './DemoPanelResultState';
import './demo-home.css';

const IDLE_AUTOSTART_MS = 5200;

export interface InteractiveDemoPanelProps {
  embedded?: boolean;
}

export default function InteractiveDemoPanel({ embedded = false }: InteractiveDemoPanelProps) {
  const { phase, homepageDemoAutoplayDisabled, run, disableHomepageDemoAutoplay, homepageDemoTimerGeneration } =
    useDemoFlow();
  const timersRef = useRef<number[]>([]);
  const lastTimerGenRef = useRef(0);
  const [fadeKey, setFadeKey] = useState(0);

  const clearTimers = () => {
    timersRef.current.forEach((t) => window.clearTimeout(t));
    timersRef.current = [];
  };

  const engage = () => {
    disableHomepageDemoAutoplay();
    clearTimers();
  };

  useEffect(() => {
    const g = homepageDemoTimerGeneration;
    if (g !== lastTimerGenRef.current) {
      if (g > 0) clearTimers();
      lastTimerGenRef.current = g;
    }
  }, [homepageDemoTimerGeneration]);

  useEffect(() => {
    timersRef.current.push(
      window.setTimeout(() => {
        if (getDemoFlowSnapshot().homepageDemoAutoplayDisabled) return;
        if (getDemoFlowSnapshot().phase !== 'idle') return;
        run();
      }, IDLE_AUTOSTART_MS),
    );
    return () => clearTimers();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    setFadeKey((k) => k + 1);
  }, [phase]);

  const fadeMs = prefersReducedMotion() ? 0 : 220;
  const Wrapper = (embedded ? 'div' : 'section') as ElementType;

  const stateContent =
    phase === 'idle' ? (
      <DemoPanelInputState onEngage={engage} />
    ) : phase === 'running' ? (
      <DemoPanelLoadingState />
    ) : (
      <DemoPanelResultState />
    );

  return (
    <Wrapper
      id="demo"
      className={cn(
        'demo-product-section relative scroll-mt-24',
        embedded && 'demo-product-section--embedded',
      )}
      aria-label="GeoScore interactive preview"
    >
      <div className="demo-product-wrap relative mx-auto w-full max-w-5xl">
        <div className="demo-product-shell geo-glass-soft rounded-2xl" aria-busy={phase === 'running'}>
          <div className="demo-product-body">
            <div
              key={fadeKey}
              className="demo-state-layer"
              style={{
                animation: fadeMs
                  ? `demo-panel-fade-in ${fadeMs}ms ease forwards`
                  : undefined,
              }}
            >
              {stateContent}
            </div>
          </div>
        </div>
      </div>
    </Wrapper>
  );
}

// frontend/src/lib/components/home/InteractiveDemoPanel.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fade } from 'svelte/transition';
  import { get } from 'svelte/store';
  import { prefersReducedMotion } from '$lib/actions/reveal';
  import {
    phase,
    run,
    disableHomepageDemoAutoplay,
    homepageDemoAutoplayDisabled,
    homepageDemoTimerGeneration,
  } from '$lib/stores/demoFlow';
  import DemoPanelInputState from './DemoPanelInputState.svelte';
  import DemoPanelLoadingState from './DemoPanelLoadingState.svelte';
  import DemoPanelResultState from './DemoPanelResultState.svelte';

  /** When true, panel sits inside the hero (no extra section chrome / looser min-height). */
  export let embedded = false;

  const IDLE_AUTOSTART_MS = 5200;

  let timers: number[] = [];

  function clearTimers() {
    timers.forEach((t) => window.clearTimeout(t));
    timers = [];
  }

  function engage() {
    disableHomepageDemoAutoplay();
    clearTimers();
  }

  let lastTimerGen = 0;
  $: {
    const g = $homepageDemoTimerGeneration;
    if (g !== lastTimerGen) {
      if (g > 0) clearTimers();
      lastTimerGen = g;
    }
  }

  onMount(() => {
    timers.push(
      window.setTimeout(() => {
        if (get(homepageDemoAutoplayDisabled)) return;
        if (get(phase) !== 'idle') return;
        run();
      }, IDLE_AUTOSTART_MS)
    );
    return () => clearTimers();
  });

  $: fadeMs = prefersReducedMotion() ? 0 : 260;
</script>

<svelte:element
  this={embedded ? 'div' : 'section'}
  id="demo"
  class="demo-product-section relative overflow-visible scroll-mt-24 {embedded
    ? 'demo-product-section--embedded'
    : ''}"
  aria-label="GeoScore interactive preview"
>
  <div class="relative mx-auto max-w-xl">
    <div
      class="demo-product-shell geo-glass-soft demo-product-stage rounded-2xl {embedded ? 'demo-product-stage--embedded' : ''}"
      aria-busy={$phase === 'running'}
    >
      {#if $phase === 'idle'}
        <div
          class="demo-state-pad"
          in:fade={{ duration: fadeMs }}
          out:fade={{ duration: fadeMs }}
        >
          <DemoPanelInputState onEngage={engage} />
        </div>
      {:else if $phase === 'running'}
        <div
          class="demo-state-pad"
          in:fade={{ duration: fadeMs }}
          out:fade={{ duration: fadeMs }}
        >
          <DemoPanelLoadingState />
        </div>
      {:else}
        <div
          class="demo-state-pad demo-state-pad--results"
          in:fade={{ duration: fadeMs }}
          out:fade={{ duration: fadeMs }}
        >
          <DemoPanelResultState />
        </div>
      {/if}
    </div>
  </div>
</svelte:element>

<style>
  :global(:root) {
    --demo-panel-divider: color-mix(in srgb, var(--border-soft) 85%, transparent);
  }

  .demo-product-section--embedded {
    padding-bottom: 0;
    margin-top: 0;
  }

  .demo-product-stage {
    position: relative;
    overflow: hidden;
    width: 100%;
    min-height: clamp(380px, 48vh, 560px);
    display: flex;
    flex-direction: column;
    background: transparent;
  }

  .demo-product-stage--embedded {
    /*
     * Reserve enough vertical space for the largest state (results) so the
     * homepage doesn't reflow as the demo advances from input -> loading -> result.
     * This keeps the viewport steady even if the user is reading sections below.
     */
    min-height: clamp(780px, 78vh, 940px);
  }

  .demo-product-shell {
    --demo-shell-radius: clamp(22px, 2.4vw, 30px);
    border-radius: var(--demo-shell-radius);
    width: 100%;
  }

  .demo-state-pad {
    flex: 1;
    display: flex;
    flex-direction: column;
    padding: clamp(1.25rem, 3vw, 2.25rem);
    min-height: inherit;
  }

  .demo-state-pad--results {
    padding-top: clamp(1.15rem, 2.5vw, 1.75rem);
  }

  @media (max-width: 1023px) {
    .demo-product-stage--embedded {
      min-height: clamp(720px, 92vw, 860px);
    }
  }

  @media (max-width: 767px) {
    .demo-product-stage--embedded {
      min-height: auto;
    }
  }
</style>
