// frontend/src/lib/components/ConsultantCorner.tsx

export interface ConsultantInsights {
  strategic_overview: string;
  the_edge: string;
  the_blindspot: string;
  the_power_move: string;
}

export interface ConsultantCornerProps {
  insights?: ConsultantInsights | null;
  confidence?: number;
}

export default function ConsultantCorner({
  insights = null,
  confidence = 0,
}: ConsultantCornerProps) {
  if (!insights) {
    return (
      <div className="my-6 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-6 text-center italic text-slate-400">
        AI Consultant analysis will appear here after site validation...
      </div>
    );
  }

  return (
    <div className="my-6 rounded-2xl border-2 border-indigo-100 bg-gradient-to-br from-indigo-50 to-white p-6 shadow-sm">
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-2xl">🤖</span>
          <h3 className="text-lg font-bold text-indigo-900">Consultant&apos;s Strategic Analysis</h3>
        </div>
        <div className="rounded-full bg-indigo-200 px-2 py-1 text-xs font-medium text-indigo-700">
          Confidence: {Math.round(confidence * 100)}%
        </div>
      </div>

      <p className="mb-6 font-medium italic leading-relaxed text-indigo-800">
        &ldquo;{insights.strategic_overview}&rdquo;
      </p>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div className="rounded-xl border border-indigo-100 bg-white p-4 shadow-sm">
          <div className="mb-2 flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-green-600">
            <span>🚀</span> The Edge
          </div>
          <p className="text-sm leading-snug text-slate-600">{insights.the_edge}</p>
        </div>

        <div className="rounded-xl border border-indigo-100 bg-white p-4 shadow-sm">
          <div className="mb-2 flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-amber-600">
            <span>⚠️</span> The Blindspot
          </div>
          <p className="text-sm leading-snug text-slate-600">{insights.the_blindspot}</p>
        </div>

        <div className="rounded-xl border border-indigo-100 bg-white p-4 shadow-sm">
          <div className="mb-2 flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-indigo-600">
            <span>💡</span> Power Move
          </div>
          <p className="text-sm leading-snug text-slate-600">{insights.the_power_move}</p>
        </div>
      </div>
    </div>
  );
}

// frontend/src/lib/components/ConsultantCorner.svelte
<script lang="ts">
  import { fade } from 'svelte/transition';

  export let insights: {
    strategic_overview: string;
    the_edge: string;
    the_blindspot: string;
    the_power_move: string;
  } | null = null;
  
  export let confidence: number = 0;
</script>

{#if insights}
  <div 
    transition:fade 
    class="my-6 p-6 rounded-2xl border-2 border-indigo-100 bg-gradient-to-br from-indigo-50 to-white shadow-sm"
  >
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center gap-2">
        <span class="text-2xl">🤖</span>
        <h3 class="text-lg font-bold text-indigo-900">Consultant's Strategic Analysis</h3>
      </div>
      <div class="text-xs font-medium px-2 py-1 bg-indigo-200 text-indigo-700 rounded-full">
        Confidence: {Math.round(confidence * 100)}%
      </div>
    </div>

    <p class="text-indigo-800 font-medium mb-6 leading-relaxed italic">
      "{insights.strategic_overview}"
    </p>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div class="p-4 rounded-xl bg-white border border-indigo-100 shadow-sm">
        <div class="flex items-center gap-2 mb-2 text-green-600 font-bold text-sm uppercase tracking-wider">
          <span>🚀</span> The Edge
        </div>
        <p class="text-sm text-slate-600 leading-snug">{insights.the_edge}</p>
      </div>

      <div class="p-4 rounded-xl bg-white border border-indigo-100 shadow-sm">
        <div class="flex items-center gap-2 mb-2 text-amber-600 font-bold text-sm uppercase tracking-wider">
          <span>⚠️</span> The Blindspot
        </div>
        <p class="text-sm text-slate-600 leading-snug">{insights.the_blindspot}</p>
      </div>

      <div class="p-4 rounded-xl bg-white border border-indigo-100 shadow-sm">
        <div class="flex items-center gap-2 mb-2 text-indigo-600 font-bold text-sm uppercase tracking-wider">
          <span>💡</span> Power Move
        </div>
        <p class="text-sm text-slate-600 leading-snug">{insights.the_power_move}</p>
      </div>
    </div>
  </div>
{:else}
  <div class="my-6 p-6 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 text-center text-slate-400 italic">
    AI Consultant analysis will appear here after site validation...
  </div>
{/if}
